/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/Cycle_Glb.glb --shadows 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./Cycle_Glb.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane060.geometry} material={materials.Cycle} position={[0, -0.577, 0]} scale={6.681} />
    </group>
  )
}

useGLTF.preload('./Cycle_Glb.glb')
